### ISSUE TITLE
Move all github actions to seperate repository

### ISSUE THREAD

**Issue by zakpaw** [DataScienceClubPG/sairn-github-actions#1]
Be **very careful** with the information that is included in the actions as for the sake of simplicity this repository is `public`!
So please make sure that **the actions are using secrets, not hardcoded credentials** to any of our resources.

Maybe usefull: 
 - this can for sure be achieved through publishing the action to the github marketplace, but it would be nice to have a simpler solution, maybe [this](https://stackoverflow.com/questions/65487925/work-with-action-from-another-organization) will help
 - [our actions documentation](https://github.com/DataScienceClubPG/sairn-documentation/blob/main/docs/research/github-actions.md)

Requirements:
 - [ ] all of the actions from different repositories are moved to this one
 - [ ] all other repositories keep their functionality, meaning that they reference this repository to run the actions
 - [ ] add markdown and yaml linters (action in [our documentation](https://github.com/DataScienceClubPG/sairn-documentation)) to every repository
   - in case some actions fail, I'll create an issue in the repository to fix it

Remember not to affect any of the `main` branches (create pull request in all modified repos and assign them to this issue)!

**Comment by zakpaw** [comment]
https://docs.github.com/en/actions/using-workflows/reusing-workflows
Takie cos mi sie jeszcze napatoczylo (nie czytalem)

**Comment by olaaaf** [comment]
- [ ] in the future - use static fields as parameters for the workflows
- [ ] secrets passing

**Comment by kangshung** [comment]
@olaaaf podepniesz oba pull requesty?

**Comment by kangshung** [comment]
- [documentation](https://github.com/DataScienceClubPG/sairn-documentation/issues/60)
- [infrastrucure](https://github.com/DataScienceClubPG/sairn-infrastructure/issues/14)

zadanie zamykam
